### ISSUE TITLE
Docs build tracks latest docs but shows old version

### ISSUE THREAD

**Issue by tk-woven** [TRI-ML/dgp#116]
# Description

See the live documentation [here](https://tri-ml.github.io/dgp/). In the upper-left corner, we mention DGP 1.0. At the time of this writing, though, we are on v1.3.

# Improvement

Either automate part of the release process to bump version numbers in docs before building them, for example as part of a GitHub Actions workflow, or do this manually around the time of a version release.

**Comment by tk-woven** [comment]
BTW, @ryo-takahashi-1206 , @ykkawana-woven , this might be a good first issue if you have time and want to learn about how some things like docs are built in DGP.

**Comment by ryo-takahashi-1206** [comment]
@tk-woven 
Thank you.  
TBH, in `dgp.git`, I haven't done a lot except working with .proto so far.  
I also think this minor bug fix is a good starting point to share maintainers' chores with Arene AI members.
I will post something within a few days 🙇

**Comment by tk-woven** [comment]
Thanks; no worries, and no rush :) This is not the highest priority, but it is a bug we should fix eventually. I'm not a master of DGP either, but let me know if you have any questions!

**Comment by ryo-takahashi-1206** [comment]
> Either automate part of the release process to bump version numbers in docs before building them,
> for example as part of a GitHub Actions workflow, or do this manually around the time of a version release.

I feel like working on the former because:

* currently we push the doc from the latest of `master`.
* in this sense, I personally feel weird if we label the doc with some tag

Therefore, I'm now planning to embed ` git describe --tags --match 'v[0-9]*.[0-9]*'` (e.g. `v1.4-2-g7da558d`).  
Please let me know if someone has another opinion

Of course, it's ideal if we can fold all the past tags in Sphinx, though.
Please let me try this next time :)

**Comment by tk-woven** [comment]
Sounds great to me! Thanks :)
